#!/usr/bin/env bash
#startup script

_ps=(waybar)
for _prs in "${_ps[@]}"; do 
	if [[ `pidof ${_prs}` ]]; then 
		killall -9 ${_prs}
	fi
done

# waybar -c ~/.config/waybar/config &
waybar -c ~/.config/hypr/waybar/config &

~/.config/hypr/scripts/wallpaper &
~/.config/hypr/scripts/idle & 
