# Shell variables
# Generated by 'wal'
wallpaper='/home/bryart/Pictures/wallpapers/wallpaper-12.jpg'

# Special
background='#091114'
foreground='#dddfe0'
cursor='#dddfe0'

# Colors
color0='#091114'
color1='#728DA1'
color2='#9BA2A9'
color3='#94A9B7'
color4='#C8BEB6'
color5='#AAB9C2'
color6='#BBC3C8'
color7='#dddfe0'
color8='#9a9c9c'
color9='#728DA1'
color10='#9BA2A9'
color11='#94A9B7'
color12='#C8BEB6'
color13='#AAB9C2'
color14='#BBC3C8'
color15='#dddfe0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
